INSERT INTO tb_book (title, number_of_pages, publication_date) VALUES ('O Senhor dos Anéis: A Sociedade do Anel', 423, '1954-07-29');
INSERT INTO tb_book (title, number_of_pages, publication_date) VALUES ('O Hobbit', 310, '1937-09-21');
INSERT INTO tb_book (title, number_of_pages, publication_date) VALUES ('Harry Potter e a Pedra Filosofal', 223, '1997-06-26');
INSERT INTO tb_book (title, number_of_pages, publication_date) VALUES ('Dom Quixote', 1056, '1605-01-16');
INSERT INTO tb_book (title, number_of_pages, publication_date) VALUES ('Cem Anos de Solidão', 417, '1967-06-05');
INSERT INTO tb_book (title, number_of_pages, publication_date) VALUES ('Orgulho e Preconceito', 279, '1813-01-28');
INSERT INTO tb_book (title, number_of_pages, publication_date) VALUES ('1984', 328, '1949-06-08');
INSERT INTO tb_book (title, number_of_pages, publication_date) VALUES ('Admirável Mundo Novo', 311, '1932-08-30');
INSERT INTO tb_book (title, number_of_pages, publication_date) VALUES ('A Revolução dos Bichos', 112, '1945-08-17');
INSERT INTO tb_book (title, number_of_pages, publication_date) VALUES ('Crime e Castigo', 671, '1866-01-01');
INSERT INTO tb_book (title, number_of_pages, publication_date) VALUES ('O Morro dos Ventos Uivantes', 416, '1847-12-17');
INSERT INTO tb_book (title, number_of_pages, publication_date) VALUES ('Jane Eyre', 500, '1847-10-16');
INSERT INTO tb_book (title, number_of_pages, publication_date) VALUES ('O Grande Gatsby', 180, '1925-04-10');
INSERT INTO tb_book (title, number_of_pages, publication_date) VALUES ('Moby Dick', 635, '1851-10-18');
INSERT INTO tb_book (title, number_of_pages, publication_date) VALUES ('O Apanhador no Campo de Centeio', 214, '1951-07-16');
INSERT INTO tb_book (title, number_of_pages, publication_date) VALUES ('As Crônicas de Nárnia: O Leão, a Feiticeira e o Guarda-Roupa', 208, '1950-10-16');
INSERT INTO tb_book (title, number_of_pages, publication_date) VALUES ('Os Miseráveis', 1463, '1862-04-03');
INSERT INTO tb_book (title, number_of_pages, publication_date) VALUES ('Drácula', 418, '1897-05-26');
INSERT INTO tb_book (title, number_of_pages, publication_date) VALUES ('Frankenstein', 280, '1818-01-01');
INSERT INTO tb_book (title, number_of_pages, publication_date) VALUES ('A Divina Comédia', 798, '1320-01-01');